es_host = "localhost:9201"
condor_index = "condor"
userprio_index = "userprio"
status_index = "status"
hadoop_index = "hadoop"
transferstats_index = "transferstats"
namenode_host = "proxy-1.t2.ucsd.edu:50070"
