{
 "title": "Hadoop",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Fractional usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Used",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "usedfrac", "id": "1", "type": "avg" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "totalbytes", "id": "3", "settings": { "script": "_value / 1024/1024/1024/1024" }, "type": "avg" }
     ],
     "timeField": "date"
    },
    {
     "alias": "Used",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "usedbytes", "id": "1", "settings": { "script": "_value / 1024/1024/1024/1024" }, "type": "avg" }
     ],
     "timeField": "date"
    },
    {
     "alias": "Free",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "freebytes", "id": "1", "settings": { "script": "_value / 1024/1024/1024/1024" }, "type": "avg" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Node counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Live",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "numlivenodes", "id": "3", "type": "avg" }
     ],
     "timeField": "date"
    },
    {
     "alias": "Dead",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "numdeadnodes", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "timeField": "date"
    },
    {
     "alias": "Decommissioned",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "numdecomnodes", "id": "1", "type": "avg" }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Live",
     "metrics": [
      {
       "hide": false,
       "id": "3",
       "settings": { "size": "100" },
       "type": "raw_data"
      }
     ],
     "timeField": "date"
    }
   ]
  }
 ]
}