{
 "title": "Transfer stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "intervals",
    "query": "10m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "If there is excessive upload,\nyou may be transferring input files to each job which are too large (or too many).\nIf there is excessive download, you may be transferring back large root files (job outputs), or very large stdout/stderr log files.\n\n`uaf-1`, `uaf-7`, and `uaf-8` each have a maximum bandwidth of 120 MB/s. If maxed out, this causes\nissues for interactive use. `uaf-10` has a bandwidth of 1 GB/s.\n         "
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "CompletionDate"
    }
   ]
  },
  {
   "title": "Job counts",
   "type": "graph",
   "description": "From `condor_status`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Held",
     "bucketAggs": [
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalHeldJobs", "id": "1", "type": "avg" }
     ],
     "query": "Name:all",
     "timeField": "LastHeardFrom"
    },
    {
     "alias": "Running",
     "bucketAggs": [
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalRunningJobs", "id": "1", "type": "avg" }
     ],
     "query": "Name:all",
     "timeField": "LastHeardFrom"
    },
    {
     "alias": "Idle",
     "bucketAggs": [
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalIdleJobs", "id": "1", "type": "avg" }
     ],
     "query": "Name:all",
     "timeField": "LastHeardFrom"
    }
   ]
  },
  {
   "title": "Number of running shadow processes",
   "type": "graph",
   "description": "From `condor_status`",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ShadowsRunning", "id": "1", "type": "avg" }
     ],
     "timeField": "LastHeardFrom"
    }
   ]
  },
  {
   "title": "Condor daemon duty cycle [%]",
   "type": "graph",
   "description": "At 98%, jobs stop matching",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "DaemonCoreDutyCycle",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "LastHeardFrom"
    }
   ]
  },
  {
   "title": "File transfer download",
   "type": "graph",
   "description": "From `condor_status`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "FileTransferDownloadBytesPerSecond_5m",
       "id": "1",
       "type": "avg"
      }
     ],
     "timeField": "LastHeardFrom"
    }
   ]
  },
  {
   "title": "File transfer upload",
   "type": "graph",
   "description": "From `condor_status`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "LastHeardFrom", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "FileTransferUploadBytesPerSecond_5m",
       "id": "1",
       "type": "avg"
      }
     ],
     "timeField": "LastHeardFrom"
    }
   ]
  }
 ]
}